### ISSUE TITLE
Using 3.5.0 (gradle-5.4.1), you must import time lib too, not just time-android

### ISSUE THREAD

**Issue by KushtrimPacaj** [kizitonwose/Time#10]
Just updated an older project where I was using this library to Android Gradle Plugin 3.5.0 ( gradle wrapper dist gradle-5.4.1 ). 
Initially I was just using ` implementation 'com.github.kizitonwose.time:time-android:1.0.2'` as instructed in the readme, and it was working.

After update, there were many errors ( e.g. extension functions on Int like .seconds were on red - not found ). Weirdly the  `time:1.0.2` classes somehow aren't in classpath anymore .
The workaround solution was to add  `time:1.0.2` as direct dependency of the project, but it should be checked what did 3.5.0 break.

I'll give it a shot on fixing and make a PR when I have some free time

**Comment by atdan** [comment]
I am having the same issue, please can you explain how you worked around it?

**Comment by KushtrimPacaj** [comment]
Add time and time-android as direct dependency:
```
implementation 'com.github.kizitonwose.time:time:1.0.2'
implementation 'com.github.kizitonwose.time:time-android:1.0.2'
```

**Comment by atdan** [comment]
It seems to have been fixed in `implementation 'com.github.kizitonwose.time:time-android:1.0.3'`

**Comment by KushtrimPacaj** [comment]
Nice. I'll close this issue then.
