### ISSUE TITLE
Operator extension functions do not support time intervals longer than Int.MAX_VALUE

### ISSUE THREAD

**Issue by jaredrummler** [kizitonwose/Time#11]
**Reproduction steps**

1) Create a time interval for years:

```kotlin
class Year : TimeUnit {
    override val timeIntervalRatio = 31_556_952.0
}

val Number.years: Interval<Year>
	get() = Interval(this)
```

2) Create a Calendar instance and add 1 year:

```kotlin
val cal = Calendar.getInstance() + 1.years
```

**Expected behavior**

The calendar instance adds 1 year to the current time.

**Actual behavior**

1 year is not added to the calendar instance.

----

If you change the following extensions functions to use `timeInMillis` instead of converting the long to an int and using `Calendar#add` it would fix the intended behavior for time intervals over `Int.MAX_VALUE`:

```kotlin
operator fun Calendar.plus(other: Interval<TimeUnit>): Calendar = (clone() as Calendar).apply {
    timeInMillis += other.inMilliseconds.longValue
}

operator fun Calendar.minus(other: Interval<TimeUnit>): Calendar = (clone() as Calendar).apply {
    timeInMillis -= other.inMilliseconds.longValue
}
```

**Comment by kizitonwose** [comment]
Thank you for bringing this up, it's now included in [1.0.4](https://github.com/kizitonwose/Time/releases/tag/1.0.4)
